spring:
  profiles: dev
  jpa:
    database: H2
---
spring:
  profiles: production
  jpa:
    database: POSTGRESQL
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}