spring:
  profiles: dev
  jpa:
    database: H2
---
spring:
  profiles: production
  jpa:
    database: POSTGRESQL
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}